// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelRun() {
  return window['go']['main']['App']['CancelRun']();
}

export function ClearAccessToken() {
  return window['go']['main']['App']['ClearAccessToken']();
}

export function FetchFiles() {
  return window['go']['main']['App']['FetchFiles']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenInputFileDialog() {
  return window['go']['main']['App']['OpenInputFileDialog']();
}

export function OpenOutputDirectoryDialog() {
  return window['go']['main']['App']['OpenOutputDirectoryDialog']();
}

export function RunCLIFetch(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['RunCLIFetch'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SetAccessToken(arg1) {
  return window['go']['main']['App']['SetAccessToken'](arg1);
}

export function ShowDialog() {
  return window['go']['main']['App']['ShowDialog']();
}
