// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelRun():Promise<void>;

export function ClearAccessToken():Promise<void>;

export function FetchFiles():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function OpenInputFileDialog():Promise<string>;

export function OpenOutputDirectoryDialog():Promise<string>;

export function RunCLIFetch(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:boolean,arg7:boolean):Promise<string>;

export function SetAccessToken(arg1:string):Promise<void>;

export function ShowDialog():Promise<void>;
